### ISSUE TITLE
ImportError when I try to import Pushbullet, nothing suggested online has worked to resolve it

### ISSUE THREAD

**Issue by ajmcateer** [rbrcsk/pushbullet.py#115]
I get 

ImportError: cannot import name 'Pushbullet' when I try to use pushbullet from Windows using Visual Studio Code.

I tried installing and adding cygwin to the Path variable and installing libmagic from there but that didn't help. 

What are the steps if any to get pushbullet.py working on Windows?

**Comment by paolobomb** [comment]
similar issue but on linux using both Python2 and 3

**Comment by kovacsbalu** [comment]
Hi @paolobomb can you please give more details?

**Comment by paolobomb** [comment]
Already solved. 
I called my script pushbullet.py and cause an exception can’t import name Pushbullet. 

Paolo Gissi
