### ISSUE TITLE
gevent issue

### ISSUE THREAD

**Issue by SimplySynced** [rbrcsk/pushbullet.py#133]
Working on using this within the project SimplyFishy found on my github.  However when I try to use this with your library and twilio I get the following issue.  

https://pastebin.com/acvFhV6Z

It looks to be due to this plugin and a few other people reviewing this as well.

**Comment by simonporter007** [comment]
I'm no expert in this area but from your stack trace it looks like a gevent error after pushbulletpy calls requests to post to pushbullet API.

I don't see pushbulletpy at fault here, it looks like you're running it under gunicorn which can use gevent and therefore the error might be with your implementation of it. At least that's what I gather from a bit of googling and reading the exact same issues on the gevent github page. For reference pushbulletpy only uses requests, websocket client and python magic.

Happy to be wrong if someone else is more versed in this area but I think you'd get better support over on gevent github.
