### ISSUE TITLE
ImportError: cannot import name Pushbullet

### ISSUE THREAD

**Issue by Cristianistrate** [rbrcsk/pushbullet.py#134]
Hi,
After I installed the lib on 2.7 Win x64 it worked. After reboot I got cannot import Pushbullet
The solution: uninstall Python, reinstall and it works but after first reboot the same issue.
Please help. On Raspbian is ok!

**Comment by simonporter007** [comment]
How did you install the library? Are you using virtualenv or anything similar? Have you searched the sys.path for the pushbulletpy dir?


```python
import sys
for path in sys.path:
  print(path)
```

**Comment by Cristianistrate** [comment]
Install:
python setup.py install
no virtualenv
result from print(path):

C:/Python27
C:\Python27\Lib\idlelib
C:\WINDOWS\SYSTEM32\python27.zip
C:\Python27\DLLs
C:\Python27\lib
C:\Python27\lib\plat-win
C:\Python27\lib\lib-tk
C:\Python27
C:\Python27\lib\site-packages

**Comment by simonporter007** [comment]
Can you confirm pushbullet directory gets created in site-packages once you install first time? Is it there on the next reboot?

If the directory is removed it sounds like there's some external issue going on. pushbulletpy certainly shouldn't unload itself from site-packages.

**Comment by Cristianistrate** [comment]
Yes:
C:\Python27\Lib\site-packages\pushbullet

**Comment by simonporter007** [comment]
And does it exist on reboot?

**Comment by Cristianistrate** [comment]
Yes

**Comment by simonporter007** [comment]
It doesn't sound like an issue with pushbulletpy then. Good luck.
