### ISSUE TITLE
ImportError: cannot import name 'Pushbullet'

### ISSUE THREAD

**Issue by harunresitc** [rbrcsk/pushbullet.py#137]
I installed it with pip method to Raspberry but it gives an error.

My codes:
```
#!/usr/bin/env python

#https://github.com/randomchars/pushbullet.py

from pushbullet import Pushbullet

api_key="o.eVxdltA46bw3Xbd00Mst9MrtCgbE8al2"
pb = Pushbullet(api_key)

print(pb.devices)
```

**Comment by simonporter007** [comment]
How exactly did you install via pip? What python version are you running?

I've tried from a fresh vagrant using pip and it works no problems with the above code. So I am presuming that your installation via pip is not in a directory that python is searching for modules on.

Also, I would highly suggest removing your api_key from your post, you are giving people free access to use your account!

**Comment by Ilhicas** [comment]
@harunresitc, as suggested by @simonporter007  delete you api key now!
