### ISSUE TITLE
Update pip package

### ISSUE THREAD

**Issue by BlackLight** [rbrcsk/pushbullet.py#139]
[The version of pushbullet.py on pip](https://pypi.org/project/pushbullet.py/) hasn't been updated since July 2017 and it's currently broken because of the changes on the arguments required by the websocket callbacks fixed in [01c791c1](https://github.com/rbrcsk/pushbullet.py/commit/01c791c13748aca9f55c1c3d51ed635f0a0f3fd4). Time to update the version of pushbullet.py on pip?

**Comment by kovacsbalu** [comment]
Hi @BlackLight, I tried to create a new release but unfortunately run into some pypi error.
Maybe @r-darwish can help. :)
[https://travis-ci.org/rbrcsk/pushbullet.py/jobs/472789439](url)

**Comment by BlackLight** [comment]
@kovacsbalu could it be that `.travis.yml` is configured to perform the upload through the legacy method instead of [twine](https://pypi.org/project/twine/)?

**Comment by kovacsbalu** [comment]
Yes, maybe. But I have no access to pushbullet.py pypi account.

**Comment by GustavoKatel** [comment]
It says:
```
HTTPError: 400 Client Error: User 'randomchars' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
```

It's using wrong access information?

**Comment by woodyl** [comment]
Just spent quite a while debugging an app that was failing because of this problem.  Is there some resolution to updating the repos?  Does this require creating a new pypi application with a different name and account?
