### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WebsocketApp'

### ISSUE THREAD

**Issue by saifulmdlw** [rbrcsk/pushbullet.py#145]
AttributeError: 'module' object has no attribute 'WebsocketApp'

I have done pip uninstall websocket-client and the install websocket-client back, but still got the same error.. can someone help me with this error.? really need help

**Comment by marcusRB** [comment]
Hi,

with pushubllet v0.12.0 and websocket-client 1.0.1 again same AttributeError

I tried:

- downgraded pushbullet (version 0.9x, 0.10x) and same error.
- downgraded websocket-client version and still AttributeError

 
**AttributeError: module 'websocket' has no attribute 'WebSocketApp'** on GoogleColab Python 3.7
