### ISSUE TITLE
Push 0.11.1 to PyPi

### ISSUE THREAD

**Issue by xerxes87** [rbrcsk/pushbullet.py#149]
Hi @rbrcsk,
would you mind pushing version 0.11.1 to PyPi, it is needed to fix Home Assistant's Pushbullet sensor: https://github.com/home-assistant/home-assistant/issues/23794
Thnak you!

**Comment by rbrcsk** [comment]
Hey @xerxes87 👋,

I've pushed a 0.11.2 version, hope it fixes your problem.
