### ISSUE TITLE
How to check Android notification(sync) using Api ?

### ISSUE THREAD

**Issue by gokulyc** [rbrcsk/pushbullet.py#150]
![image](https://user-images.githubusercontent.com/13468848/81500548-76227f00-92f0-11ea-8368-be58f61ccf82.png)

**Comment by rbrcsk** [comment]
Hey @gokulyc 👋

I believe this example has what you're looking for: https://github.com/rbrcsk/pushbullet.py/blob/master/example/mirror_example.py
