### ISSUE TITLE
Avoid using mocks in the tests

### ISSUE THREAD

**Issue by r-darwish** [rbrcsk/pushbullet.py#64]
Most of our tests use mocks instead of contacting the real Pushbullet. As I said in #63, I don't think that it's such a good idea because our tests will pass even if Pushbullet change the API. As stated in #57, the "contacts" API has been obsolete for a while and our tests didn't detect that breakage.

**Comment by kovacsbalu** [comment]
Hi @r-darwish,
in my view these tests are unit test and as I understand you need integration tests. So, feel free to write some.
